FROM openjdk:17-alpine

WORKDIR /app

RUN addgroup -S coderunner && adduser -S coderunner -G coderunner

COPY execute-java.sh /app/execute.sh
RUN chmod +x /app/execute.sh

USER coderunner

CMD ["/bin/sh"]