FROM python:3.11-alpine

WORKDIR /app

RUN addgroup -S coderunner && adduser -S coderunner -G coderunner

RUN pip install --no-cache-dir numpy

COPY --chown=coderunner:coderunner execute-py.sh /app/execute.sh
RUN chmod +x /app/execute.sh

USER coderunner

ENTRYPOINT ["/app/execute.sh"]