FROM openjdk:17-alpine

WORKDIR /app

RUN addgroup -S coderunner && adduser -S coderunner -G coderunner

COPY --chown=coderunner:coderunner execute-java.sh /app/execute.sh
RUN chmod +x /app/execute.sh

USER coderunner

ENTRYPOINT ["/app/execute.sh"]